import { catchAsyncErrors } from "../middlewares/catchAsyncErrors.js";
import ErrorHandler from "../middlewares/errorMiddleware.js";
import { Appointment } from "../models/schemaOfAppointment.js";
import { User } from "../models/schemaOfUser.js";


export const postAppointment = catchAsyncErrors(async (req, res, next) => {
    const {
      firstName,
      lastName,
      email,
      phone,
      dob,
      gender,
      appointmentDate,
      department,
      doctorFirstName,
      doctorLastName,
      hasVisited,
      address,
    } = req.body;
    if (
      !firstName ||
      !lastName ||
      !email ||
      !phone ||
      !dob ||
      !gender ||
      !appointmentDate ||
      !department ||
      !doctorFirstName ||
      !doctorLastName ||
      !address
    ) {
      return next(new ErrorHandler("Please fill all the Details!", 400));
    }
    const isConflict = await User.find({
      firstName: doctorFirstName,
      lastName: doctorLastName,
      role: "Doctor",
      doctorDepartment: department,
    });
    if (isConflict.length === 0) {
      return next(new ErrorHandler("Doctor can not found", 404));
    }
  
    if (isConflict.length > 1) {
      return next(
        new ErrorHandler(
          "Error! Please contact through Email Or Phone.",404 ));
    }
    const doctorId = isConflict[0]._id;
    const patientId = req.user._id;
    const appointment = await Appointment.create({
      firstName,
      lastName,
      email,
      phone,
      dob,
      gender,
      appointmentDate,
      department,
      doctor: {
        firstName: doctorFirstName,
        lastName: doctorLastName,
      },
      hasVisited,
      address,
      doctorId,
      patientId,
    });
    res.status(200).json({
      success: true,
      message: "Appointment Send Successfully!",
      appointment,
      
    });
  });

  